import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Top from "../components/Top";
import NavBar from "@/components/layout/NavBar";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Comforty",
  description: "Generated by Asma Jawaid",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Top/>
        <Header/>
        <NavBar/>
        <main className="px-[179px]">
        {children }
       </main>
        <Footer/>
      </body>
    </html>
  );
}
